services:
  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000" # Mapea el puerto 8000 del contenedor al host
    volumes:
      - ./fastapi/data:/app/data # Mapea el directorio de la base de datos
    networks:
      - backend

  streamlit:
    build:
      context: ./streamlit
    ports:
      - "8501:8501" # Mapea el puerto 8501 del contenedor al host
    networks:
      - backend

networks:
  backend:
    driver: bridge
