services:
  fastapi:
    build: fastapi/
    ports:
      - "8000:8000"
    networks:
      - backend_network
    container_name: fastapi
    volumes:
      - ./fastapi:/app
      - mis_datos:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/sql_app.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  streamlit:
    build: streamlit/
    depends_on:
      fastapi:
        condition: service_healthy
    ports:
      - "8501:8501"
    networks:
      - backend_network
    container_name: streamlit
    volumes:
      - ./streamlit:/app  

networks:
  backend_network:
    driver: bridge
    
volumes:
   mis_datos:
